const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Button,
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Behaviors.Physics,
		C3.Behaviors.Platform,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Acts.LoadState
	];
};
self.C3_JsPropNameTable = [
	{ТайловыйФон: 0},
	{играть: 0},
	{инструкция: 0},
	{ТайловыйФон2: 0},
	{меню: 0},
	{Спрайт: 0},
	{правила: 0},
	{Спрайт2: 0},
	{ТайловыйФон3: 0},
	{ТайловыйФон4: 0},
	{ТайловыйФон5: 0},
	{ТайловыйФон6: 0},
	{Синусоида: 0},
	{спавнерводы: 0},
	{спавнермонет: 0},
	{спавнребомб: 0},
	{плюс: 0},
	{Физика: 0},
	{вода: 0},
	{бомба: 0},
	{Платформер: 0},
	{пушка: 0},
	{Пуля: 0},
	{ядро: 0},
	{Мышь: 0},
	{счёт: 0},
	{монетка: 0},
	{Твёрдый: 0},
	{пол: 0},
	{спавнребм: 0},
	{бм: 0},
	{Клавиатура: 0}
];

self.InstanceType = {
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	играть: class extends self.IButtonInstance {},
	инструкция: class extends self.IButtonInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	меню: class extends self.IButtonInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	правила: class extends self.ITextInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	ТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон4: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон5: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон6: class extends self.ITiledBackgroundInstance {},
	спавнерводы: class extends self.ISpriteInstance {},
	спавнермонет: class extends self.ISpriteInstance {},
	спавнребомб: class extends self.ISpriteInstance {},
	плюс: class extends self.IInstance {},
	вода: class extends self.ISpriteInstance {},
	бомба: class extends self.ISpriteInstance {},
	пушка: class extends self.ISpriteInstance {},
	ядро: class extends self.ISpriteInstance {},
	Мышь: class extends self.IInstance {},
	счёт: class extends self.ITextInstance {},
	монетка: class extends self.ISpriteInstance {},
	пол: class extends self.ISpriteInstance {},
	спавнребм: class extends self.ISpriteInstance {},
	бм: class extends self.ISpriteInstance {},
	Клавиатура: class extends self.IInstance {}
}